# Render Configuration File
# Docs: https://render.com/docs/deploy-render-yaml

services:
  - type: web
    name: priyo-chat
    env: node
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: priyo-chat-db
          property: connectionString
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://priyo-chat.onrender.com
      - key: N8N_WEBHOOK_URL
        value: https://n8n.srv958024.hstgr.cloud/webhook/e985d15f-b2f6-456d-be15-97e0b1544a40/chat
    plan: free

databases:
  - name: priyo-chat-db
    databaseName: priyo_chat
    user: priyo_user
    plan: free
